{
 "title": "Callback Service",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Tech", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "go_gc_duration_seconds", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Heap Alloc Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_heap_alloc_bytes", "legendFormat": "value" }
   ]
  },
  {
   "title": "Mem Stack",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_stack_inuse_bytes", "legendFormat": "value" }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "value" }
   ]
  },
  { "title": "Callbacks Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Callback Messages Producing Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(callback_producer_duration_milliseconds_bucket[30s])) by (vmrange))",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Callback Publishing Runs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "rate(callback_producer_total[30s])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Callback Messages Processed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "rate(callback_processor_total[30s])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Callback Sender Latencies P50",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(callback_sender_milliseconds_bucket[30s])) by (vmrange, url))",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Callback Messages Published",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "targets": [
    {
     "expr": "rate(callback_producer_messages_total[30s])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Callback Sender Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "expr": "sum by (url, status) (rate(callback_sender_milliseconds_count[30s]))",
     "legendFormat": "[{{status}}] {{url}}"
    }
   ]
  },
  {
   "title": "Callback Sender Latencies P95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(callback_sender_milliseconds_bucket[30s])) by (vmrange, url))",
     "legendFormat": "{{url}}"
    }
   ]
  },
  { "title": "Payment events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Events processed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "rate(event_processor_messages_total[30s])",
     "legendFormat": "{{result}}"
    }
   ]
  }
 ]
}